name: server
data_dir: "./data/"

logger:
  stdout: false
  level: "warn"

metrics:
  reporting_freq_sec: 60
  namespace: ""
  stackdriver_projectid: ""
  prometheus_port: 0

database:
  address:
    - "root@cockroachdb:26257"
  conn_max_lifetime_ms: 0
  max_open_conns: 0
  max_idle_conns: 100

runtime:
  env:
    - "example_apikey=example_apivalue"
    - "encryptionkey=afefa==e332*u13=971mldq"
  path: "/nakama/data/modules"
  http_key: "key"

socket:
  server_key: "key"
  port: 7350
  max_message_size_bytes: 4096 # bytes
  read_timeout_ms: 40000
  write_timeout_ms: 40000
  idle_timeout_ms: 120000
  write_wait_ms: 5000
  pong_wait_ms: 12000
  ping_period_ms: 10000 # Must be less than pong_wait_ms
  outgoing_queue_size: 16

session:
  encryption_key: "key"
  token_expiry_sec: 604800

social:
  steam:
    publisher_key: ""
    app_id: 0

console:
  port: 7351
  username: "admin"
  password: "password"
  signing_key: "key"

cluster:
  join:
    - "10.0.0.2:7352"
    - "10.0.0.3:7352"
  gossip_bindaddr: "0.0.0.0"
  gossip_bindport: 7352
  rpc_port: 7353